### ISSUE TITLE
A War3ID must be 4 ascii characters in length (got 8) 'DummySec' when loading Warchasers from Reforged

### ISSUE THREAD

**Issue by tdauth** [Retera/WarsmashModEngine#38]
I run Warsmash from the IDE and loaded (4)warchasers.w3m exported from Reforged and got this error:

```
getAnyExtensionImageFixRGB: ReplaceableTextures\TeamColor\TeamColor06.blp (texture)
getAnyExtensionImageFixRGB: UI\Widgets\Console\Human\CommandButton\human-activebutton.blp (texture)
Exception in thread "LWJGL Application" java.lang.IllegalArgumentException: A War3ID must be 4 ascii characters in length (got 8) 'DummySec'
	at com.etheller.warsmash.util.War3ID.fromString(War3ID.java:23)
	at com.etheller.warsmash.units.manager.MutableObjectData.keySet(MutableObjectData.java:252)
	at com.etheller.warsmash.viewer5.handlers.w3x.rendersim.ability.AbilityDataUI.<init>(AbilityDataUI.java:137)
	at com.etheller.warsmash.viewer5.handlers.w3x.War3MapViewer.setGameUI(War3MapViewer.java:2580)
	at com.etheller.warsmash.WarsmashGdxMapScreen$1.onCreate(WarsmashGdxMapScreen.java:189)
	at com.etheller.warsmash.viewer5.handlers.w3x.ui.MeleeUI.main(MeleeUI.java:497)
	at com.etheller.warsmash.WarsmashGdxMapScreen.show(WarsmashGdxMapScreen.java:203)
	at com.badlogic.gdx.Game.setScreen(Game.java:61)
	at com.etheller.warsmash.viewer5.handlers.w3x.ui.MenuUI.update(MenuUI.java:1851)
	at com.etheller.warsmash.WarsmashGdxMenuScreen.render(WarsmashGdxMenuScreen.java:577)
	at com.badlogic.gdx.Game.render(Game.java:46)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:259)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:138)
```

**Comment by Retera** [comment]
war3.mpq and war3.w3mod contain mostly the same information but from different versions of Warcraft III. My advice would be that you not do this, and not try to load from two different versions of Warcraft III simultaneously.

It looks like `DummySec` is a problem with the Reforged support that must have been accidentally introduced at some point. Seems that I have a workaround on my local computer that hasn't been pushed to GitHub, so I'll try to see if I can get that sent up sometime soon.
