### ISSUE TITLE
Jass parser cannot find config function in map script

### ISSUE THREAD

**Issue by tdauth** [Retera/WarsmashModEngine#64]
I get this error in my error log:

```
Exception in thread "LWJGL Application" com.etheller.interpreter.ast.debug.JassException: Exception on Line -1
	at com.etheller.warsmash.parsers.jass.Jass2$ConfigEnvironment.config(Jass2.java:9390)
	at com.etheller.warsmash.viewer5.handlers.w3x.ui.MenuUI.loadAndCacheMapConfigs(MenuUI.java:1770)
	at com.etheller.warsmash.viewer5.handlers.w3x.ui.MenuUI.startMap(MenuUI.java:1722)
	at com.etheller.warsmash.WarsmashGdxMenuScreen.startMap(WarsmashGdxMenuScreen.java:925)
	at com.etheller.warsmash.desktop.DesktopLauncher$1.run(DesktopLauncher.java:124)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.executeRunnables(LwjglApplication.java:309)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:236)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:138)
Caused by: java.lang.IllegalStateException: Unable to spawn jass thread for function name: config
	at com.etheller.interpreter.ast.scope.GlobalScope.createThread(GlobalScope.java:570)
	at com.etheller.warsmash.parsers.jass.Jass2$ConfigEnvironment.config(Jass2.java:9384)
	... 7 more
```

The map script should be this: https://raw.githubusercontent.com/tdauth/wowr/refs/heads/master/wowr.w3x/war3map.j

There is a config function:

```
function config takes nothing returns nothing
    call SetMapName("TRIGSTR_001")
    call SetMapDescription("TRIGSTR_003")
    call SetPlayers(23)
    call SetTeams(23)
    call SetGamePlacement(MAP_PLACEMENT_TEAMS_TOGETHER)

    call DefineStartLocation(0, - 16512.0, - 22272.0)
    call DefineStartLocation(1, - 16512.0, - 22272.0)
    call DefineStartLocation(2, - 16512.0, - 22272.0)
    call DefineStartLocation(3, - 16512.0, - 22272.0)
    call DefineStartLocation(4, - 16512.0, - 22272.0)
    call DefineStartLocation(5, - 16512.0, - 22272.0)
    call DefineStartLocation(6, - 16512.0, - 22272.0)
    call DefineStartLocation(7, - 16512.0, - 22272.0)
    call DefineStartLocation(8, - 16512.0, - 22272.0)
    call DefineStartLocation(9, - 16512.0, - 22272.0)
    call DefineStartLocation(10, - 16512.0, - 22272.0)
    call DefineStartLocation(11, - 16512.0, - 22272.0)
    call DefineStartLocation(12, - 16512.0, - 22272.0)
    call DefineStartLocation(13, - 16512.0, - 22272.0)
    call DefineStartLocation(14, - 16512.0, - 22272.0)
    call DefineStartLocation(15, - 16512.0, - 22272.0)
    call DefineStartLocation(16, - 16512.0, - 22272.0)
    call DefineStartLocation(17, - 16512.0, - 22272.0)
    call DefineStartLocation(18, - 16512.0, - 22272.0)
    call DefineStartLocation(19, - 16512.0, - 22272.0)
    call DefineStartLocation(20, - 16512.0, - 22272.0)
    call DefineStartLocation(21, - 16512.0, - 22272.0)
    call DefineStartLocation(22, - 9664.0, - 25088.0)

    // Player setup
    call InitCustomPlayerSlots()
    call InitCustomTeams()
    call InitAllyPriorities()
endfunction
```
I have no idea why it is not found.

**Comment by Retera** [comment]
Be careful, on a Linux based system the "Folder" data source is often messed up because it is case sensitive. This can easily make it that your Reforged override of the Blizzard.j is not found, such as if the game requests `Scripts\Blizzard.j` but you provide `scripts/Blizzard.j` which is a different folder on Linux.

**Comment by tdauth** [comment]
You are correct. I had to rename it into "Scripts".

Now the map loading screen is shown but then it crashes with:

```
Exception in thread "LWJGL Application" java.lang.NullPointerException: Cannot invoke "com.etheller.warsmash.viewer5.handlers.w3x.simulation.players.CRace.getId()" because "race" is null
	at com.etheller.warsmash.viewer5.handlers.w3x.simulation.players.CRaceManager.get(CRaceManager.java:48)
	at com.etheller.warsmash.viewer5.handlers.w3x.ui.MeleeUI.main(MeleeUI.java:534)
	at com.etheller.warsmash.viewer5.handlers.w3x.ui.toggle.MeleeToggleUI.main(MeleeToggleUI.java:92)
	at com.etheller.warsmash.WarsmashGdxMapScreen.show(WarsmashGdxMapScreen.java:207)
	at com.badlogic.gdx.Game.setScreen(Game.java:63)
	at com.etheller.warsmash.viewer5.handlers.w3x.ui.MenuUI.update(MenuUI.java:1917)
```
